server:
  port: 8080

spring:
  application:
    name: job-queue-platform-refined

  datasource:
    url: jdbc:postgresql://localhost:5432/jobqueue
    username: jobqueue
    password: jobqueue
    driver-class-name: org.postgresql.Driver
 
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true

jwt:
  secret: "enu6pw5zve3B8RkgzWhGyysBGiyty3m9N5QMTO3g5vY="
  expiration-ms: 3600000
 
logging:
  level:
    "[org.hibernate.SQL]": debug
 
